FROM ruby:3.3-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential libpq-dev nodejs npm git curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["sleep", "infinity"]
